version: '3.4'
networks:
  net:
    driver: bridge
volumes:
  db_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: ./volume_db_data
  prometheus_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: ./volume_prometheus_data
  grafana_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: ./volume_grafana_data
services:
  web:
    image: jeisonj2019/hostvmadmin
    container_name: hostvm_app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net
    ports:
      - 8000:5000
    environment:
      - ConnectionStrings__def=Server=hostvm_db;Port=5432;Database=hostvm;Username=postgres;Password=1234
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__Console__FormatterName=simple
  db:
    image: postgres
    container_name: hostvm_db
    restart: always
    environment:
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "1234"
    networks:
      - net
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
  prometheus:
    image: prom/prometheus
    container_name: hostvm_prometheus
    depends_on:
      - web
      - db
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    user: "root"
    command: 
      --web.enable-lifecycle 
      --config.file=/etc/prometheus/prometheus.yml
    networks:
    - net
  grafana:
    image: grafana/grafana
    container_name: hostvm_grafana
    depends_on:
        - web
        - db
    ports:
      - 3000:3000
    volumes:
        - grafana_data:/var/lib/grafana
    user: "root"
    networks:
      - net 
    environment: 
        - HTTP_USER="{{grafana_user}}"
        - HTTP_PASS="{{grafana_password}}"
    restart: always
