version: '3.4'
networks:
  net:
    driver: bridge
services:
  hostvmadmin:
    image: jeisonj2019/hostvmadmin
    #image: ${DOCKER_REGISTRY-}hostvmadmin
    #build:
    #  context: .
    #  dockerfile: HostvmAdmin/Dockerfile
    container_name: hostvm_app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net
    ports:
      - 8001:80
    environment:
      - ConnectionStrings__def=Server=hostvm_db;Port=5432;Database=hostvm;Username=postgres;Password=1234
  postgres:
    image: postgres
    container_name: hostvm_db
    restart: always
    environment:
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "1234"
    networks:
      - net
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
