version: '3.4'
networks:
  net:
    driver: bridge
services:
  jaeger:
    image: jaegertracing/all-in-one
    networks:
        - net
    ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "14268:14268"
        - "9411:9411"
  hostvmadmin:
    image: jeisonj2019/hostvmadmin
    container_name: hostvm_app
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_started
    networks:
      - net
    ports:
      - 8000:80
    environment:
      - ConnectionStrings__def=Server=hostvm_db;Port=5432;Database=hostvm;Username=postgres;Password=1234
      - JAEGER_SERVICE_NAME=HostvmAdmin
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
  postgres:
    image: postgres
    container_name: hostvm_db
    restart: always
    environment:
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "1234"
    networks:
      - net
    ports:
      - 5431:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
